version: '3.3'
services:
  deployer:
    build:
      context: .
      dockerfile: DockerfileDeployer
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - 9000:8080

  router:
    build:
      context: .
      dockerfile: DockerfileRouter
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - 9000:8080
