version: '3.3'
services:
  deployer:
    build:
      context: .
      dockerfile: DockerfileDeployer
    environment:
      - AWS_PROFILE
    ports:
      - 9000:8080

  router:
    build:
      context: .
      dockerfile: DockerfileRouter
    environment:
      - AWS_PROFILE
    ports:
      - 9000:8080
