version: "3.3"
services:
  deployer:
    build:
      context: .
      dockerfile: src/PwrDrvr.MicroApps.Deployer/Dockerfile
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - 9000:8080
