name: "Install Modules"
description: "Install Node.js modules or restore cache"

inputs:
  node-version:
    description: "NodeJS Version"
    required: true
  github-pat:
    description: "github.com PAT"
    required: true
  lookup-only:
    description: "If true, only checks if cache entry exists and skips download. Does not change save cache behavior"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        token: ${{ inputs.github-pat }}

    - name: Restore Node Modules from Cache
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          apps/**/node_modules
          packages/**/node_modules
          tests/**/node_modules
          !node_modules/.cache
        key: node-modules-${{ inputs.node-version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('yarn.lock') }}
        lookup-only: ${{ inputs.lookup-only }}

    - name: Install Yarn
      shell: bash
      run: |
        if ! command -v yarn &> /dev/null
        then
          npm install -g yarn
        fi

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn --frozen-lockfile
